export const teamInfo = {
  name: "Golden State",
  abbr: "GS",
  record: "42-15",
  standing: "1st in West",
  nextMatch: {
    opponent: "Lakers",
    countdown: "02:45:00",
  },
}

export const teamStats = [
  {
    label: "PPG",
    value: "118.5",
    change: "+2.4%",
    isPositive: true,
    context: "vs League Avg (112.1)",
  },
  {
    label: "REBOUNDS",
    value: "44.2",
    change: "-1.1%",
    isPositive: false,
    context: "vs Last Week (44.8)",
  },
  {
    label: "ASSISTS",
    value: "28.9",
    change: "+5.2%",
    isPositive: true,
    context: "League Rank: #2",
  },
  {
    label: "EFFICIENCY",
    value: "112.0",
    change: "+0.8%",
    isPositive: true,
    context: "Net Rating: +8.5",
  },
]

export const playerOfWeek = {
  name: "Stephen Curry",
  number: 30,
  position: "Point Guard",
  avatar: "/avatars/curry.jpg",
  stats: {
    pts: "34.2",
    threePct: "48%",
    min: "32",
  },
}

export const upcomingSchedule = [
  {
    date: "FEB 24",
    opponent: "Lakers",
    abbr: "LAL",
    color: "#FDB927",
    time: "7:30 PM",
    isAway: true,
  },
  {
    date: "FEB 26",
    opponent: "Rockets",
    abbr: "HOU",
    color: "#CE1141",
    time: "10:00 PM",
    isAway: false,
  },
  {
    date: "FEB 28",
    opponent: "Mavs",
    abbr: "DAL",
    color: "#00538C",
    time: "8:00 PM",
    isAway: true,
  },
]

export const recentGames = [
  {
    status: "WIN",
    date: "Feb 21",
    opponent: "vs Suns",
    opponentAbbr: "PHX",
    opponentColor: "#E56020",
    result: "124 - 110",
    topScorer: "Curry (32)",
    rebounds: 48,
    assists: 34,
  },
  {
    status: "WIN",
    date: "Feb 19",
    opponent: "@ Nuggets",
    opponentAbbr: "DEN",
    opponentColor: "#0E2240",
    result: "115 - 108",
    topScorer: "Thompson (28)",
    rebounds: 42,
    assists: 30,
  },
  {
    status: "LOSS",
    date: "Feb 17",
    opponent: "vs Celtics",
    opponentAbbr: "BOS",
    opponentColor: "#007A33",
    result: "105 - 112",
    topScorer: "Curry (24)",
    rebounds: 38,
    assists: 26,
  },
  {
    status: "WIN",
    date: "Feb 15",
    opponent: "@ Kings",
    opponentAbbr: "SAC",
    opponentColor: "#5A2D81",
    result: "128 - 119",
    topScorer: "Wiggins (30)",
    rebounds: 45,
    assists: 32,
  },
  {
    status: "WIN",
    date: "Feb 13",
    opponent: "vs Clippers",
    opponentAbbr: "LAC",
    opponentColor: "#C8102E",
    result: "118 - 104",
    topScorer: "Curry (35)",
    rebounds: 44,
    assists: 29,
  },
]

export const playerProfile = {
  name: 'Marcus "The Jet" Thompson',
  number: 30,
  position: "Forward",
  height: '6\'8"',
  weight: "225 lbs",
  season: "5th Season",
  college: "Duke University",
  age: 26,
  status: "Active",
  stats: {
    pts: { value: "24.5", change: "+2.1" },
    reb: { value: "8.2", change: "+0.5" },
    ast: { value: "5.1", change: "+0.2" },
    fgPct: { value: "52%", context: "League Avg" },
  },
}

export const shotChartData = [
  { x: 38, y: 18, made: true },
  { x: 42, y: 18, made: true },
  { x: 35, y: 45, made: true },
  { x: 45, y: 45, made: false },
  { x: 50, y: 35, made: true },
  { x: 55, y: 50, made: true },
  { x: 25, y: 55, made: true },
  { x: 30, y: 70, made: false },
  { x: 70, y: 35, made: true },
  { x: 75, y: 35, made: true },
  { x: 80, y: 40, made: true },
  { x: 40, y: 60, made: true },
  { x: 45, y: 65, made: false },
  { x: 50, y: 80, made: false },
]

export const skillAnalysis = {
  player: [85, 78, 72, 65, 80],
  leagueAvg: [70, 68, 65, 62, 68],
  labels: ["Scoring", "Reb", "Def", "Play", "Eff"],
}

export const gameLog = [
  {
    date: "Oct 24",
    opponent: "vs DEN",
    result: "W 108-102",
    isWin: true,
    min: 36,
    pts: 28,
    reb: 10,
    ast: 6,
    stl: 2,
    blk: 1,
    tov: 3,
    pf: 2,
  },
  {
    date: "Oct 22",
    opponent: "@ PHX",
    result: "L 104-108",
    isWin: false,
    min: 34,
    pts: 21,
    reb: 8,
    ast: 4,
    stl: 1,
    blk: 0,
    tov: 4,
    pf: 3,
  },
  {
    date: "Oct 20",
    opponent: "vs GSW",
    result: "W 115-109",
    isWin: true,
    min: 38,
    pts: 32,
    reb: 12,
    ast: 8,
    stl: 3,
    blk: 2,
    tov: 2,
    pf: 4,
  },
  {
    date: "Oct 17",
    opponent: "@ SAC",
    result: "W 122-114",
    isWin: true,
    min: 32,
    pts: 24,
    reb: 7,
    ast: 5,
    stl: 0,
    blk: 1,
    tov: 2,
    pf: 2,
  },
  {
    date: "Oct 14",
    opponent: "vs LAL",
    result: "L 98-105",
    isWin: false,
    min: 28,
    pts: 18,
    reb: 6,
    ast: 3,
    stl: 1,
    blk: 1,
    tov: 5,
    pf: 5,
  },
]

export const scoutingData = {
  myTeam: {
    name: "Warriors",
    abbr: "GSW",
    record: "14-8",
    conference: "3rd West",
  },
  opponent: {
    name: "Suns",
    abbr: "PHX",
    record: "12-9",
    conference: "5th West",
  },
  nextGame: "7:30 PM EST",
  date: "Nov 24, 2023",
  keyThreat: {
    name: "D. Booker",
    position: "SG",
    team: "Phoenix Suns",
    ppg: "28.5",
    ast: "5.8",
    fgPct: "48%",
  },
  comparison: [
    {
      label: "POINTS PER GAME",
      myTeam: 118.4,
      opponent: 116.2,
      max: 130,
    },
    {
      label: "DEFENSIVE RATING",
      myTeam: 110.1,
      opponent: 108.5,
      max: 120,
    },
    {
      label: "PACE",
      myTeam: 101.2,
      opponent: 98.5,
      max: 110,
    },
    {
      label: "3PT PERCENTAGE",
      myTeam: 38.2,
      opponent: 36.4,
      max: 50,
    },
    {
      label: "REBOUNDS",
      myTeam: 42.5,
      opponent: 44.1,
      max: 55,
    },
  ],
  defensiveGaps: [
    { zone: "Right Wing", percentage: 42 },
    { zone: "Paint", percentage: 39 },
  ],
}
